spring:
  sql.init:
    data-locations: classpath:/testdata.sql
    mode: always
  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hbm2ddl.import_files: indexes.sql

cors:
  allowed-origins: ''
  allowed-methods: ''
  allowed-headers: ''
  allow-credentials: false
