package api.database.model.constant;

public enum ErrorGroup {
  //Objects
  WRONG_OBJECT_TRANSFER,
  //all tables
  ASSOCIATION,
  ASSOCIATION_CHANGE,
  ASSOCIATION_TYPE,
  ATTRIBUTE,
  ATTRIBUTE_CHANGE,
  ATTRIBUTE_TEMPLATE,
  BRANCHING,
  CONFIGURATION,
  EVENT,
  OBJECT,
  OBJECT_TEMPLATE,
  OBJECT_TYPE,
  PERMISSION,
  SCENARIO,
  SCENARIO_PHASE,
  SCENARIO_TO_OBJECT_TEMPLATE,
  SCENARIO_TO_OBJECT_TYPE,
  THREAD,
  THREAD_TO_OBJECT,
  USER,
  USER_TO_OBJECT,
  //
  SERVER,
}
